name: Fyne cross-compile Faceloader
on:
  push:
    tags:
      - '*'
permissions:
  contents: write
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          prerelease: true
          generate_release_notes: true
  package-faceloader-linux:
    needs: release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          fetch-depth: 0
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.19"
      - name: Install native deps
        run: |
          sudo apt update
          sudo apt install gcc libgl1-mesa-dev xorg-dev -y
      - name: Install Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.19
      - name: Go test
        run: |
          go mod tidy
          go test ./...
      - name: Install Fyne CLI
        run: |
          go install fyne.io/fyne/v2/cmd/fyne@latest
          $HOME/go/bin/fyne version
      - name: Get the version
        id: get_version
        run: echo ::set-output name=VERSION::$(echo $GITHUB_REF | cut -d / -f 3)
      - name: Fyne Package
        run: |
          $HOME/go/bin/fyne package --appVersion ${{ steps.get_version.outputs.VERSION }}
      - name: Upload package
        uses: softprops/action-gh-release@v1
        with:
          files: "faceloader.tar.xz"
  package-faceloader-mac:
    needs: release
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v5
      - name: Install Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.19
      - name: Go test
        run: |
          go mod tidy
          go test ./...
      - name: Install Fyne CLI
        run: |
          go install fyne.io/fyne/v2/cmd/fyne@latest
          $HOME/go/bin/fyne version
      - name: Get the version
        id: get_version
        run: echo ::set-output name=VERSION::$(echo $GITHUB_REF | cut -d / -f 3)
      - name: Fyne Package
        run: |
          $HOME/go/bin/fyne package --appVersion ${{ steps.get_version.outputs.VERSION }}
          zip -r faceloader-mac.zip faceloader.app
      - name: Upload package
        uses: softprops/action-gh-release@v1
        with:
          files: "faceloader-mac.zip"
